import * as fs from 'fs';
import * as path from 'path';
import { ServiceConfig, SERVICES } from '../services';

export function generateCompose(
  selectedServices: string[],
  globalVars: Record<string, string> = {}
): string {
  const allComposes: string[] = [];
  const addedServices = new Set<string>();

  for (const serviceKey of selectedServices) {
    const service = SERVICES[serviceKey];
    if (!service) continue;

    // Add dependencies first
    if (service.dependsOn) {
      for (const dep of service.dependsOn) {
        if (!addedServices.has(dep) && SERVICES[dep]) {
          const depService = SERVICES[dep];
          allComposes.push(depService.composeTemplate({ version: depService.version, ...globalVars }));
          addedServices.add(dep);
        }
      }
    }

    const vars = { version: service.version, PORT: String(service.ports[0]?.host || 8080), ...globalVars };
    allComposes.push(service.composeTemplate(vars));
    addedServices.add(serviceKey);
  }

  return allComposes.join('\n\n---\n\n');
}

export function generateBackupScript(
  selectedServices: string[],
  globalVars: Record<string, string> = {}
): string {
  const shebang = '#!/bin/bash\n\n# Auto-generated backup script\n# Run with: bash backup.sh\n\nset -e\n';
  const lines: string[] = [shebang];

  for (const serviceKey of selectedServices) {
    const service = SERVICES[serviceKey];
    if (!service) continue;
    lines.push(service.backupScript(globalVars));
    lines.push('');
  }

  lines.push('echo "All backups completed!"');
  return lines.join('\n');
}

export function generateEnvFile(
  selectedServices: string[],
  vars: Record<string, string> = {}
): string {
  const lines: string[] = [
    '# Generated by selfhosted-setup-helper',
    `# Created: ${new Date().toISOString()}`,
    '',
    '# ─── Global Settings ───',
    `PROJECT_DIR=${path.basename(process.cwd())}`,
    'COMPOSE_PROJECT_NAME=selfhosted',
    '',
  ];

  for (const serviceKey of selectedServices) {
    const service = SERVICES[serviceKey];
    if (!service) continue;

    lines.push(`\n# ─── ${service.name} ───`);
    for (const env of service.envVars || []) {
      const val = vars[`${serviceKey}_${env.key}`] || env.default || '';
      lines.push(`# ${env.description}`);
      lines.push(`${serviceKey}_${env.key}=${val}`);
    }
  }

  return lines.join('\n');
}

export function writeOutput(
  outputDir: string,
  selectedServices: string[],
  globalVars: Record<string, string>
): { compose: string; backup: string; env: string } {
  const composeContent = generateCompose(selectedServices, globalVars);
  const backupContent = generateBackupScript(selectedServices, globalVars);
  const envContent = generateEnvFile(selectedServices, globalVars);

  // Ensure output directory exists
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Write files
  const composePath = path.join(outputDir, 'docker-compose.yml');
  const backupPath = path.join(outputDir, 'backup.sh');
  const envPath = path.join(outputDir, '.env');

  fs.writeFileSync(composePath, composeContent, 'utf-8');
  fs.writeFileSync(backupPath, backupContent, 'utf-8');
  fs.writeFileSync(envPath, envContent, 'utf-8');
  fs.chmodSync(backupPath, 0o755);

  return { compose: composePath, backup: backupPath, env: envPath };
}
